name: google_maps_webservice
description: Google Maps Web Services [API](https://developers.google.com/maps/web-services)
version: 0.0.20-nullsafety.5
homepage: https://github.com/lejard-h/google_maps_webservice

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
#  http: ^1.1.0
  http: ">=1.0.0 <2.0.0"
  json_annotation: ^4.8.1
  meta: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.6
  coverage: ^1.6.3
  json_serializable: ^6.7.1
  lints: ^2.1.1
  test: ^1.24.4
